// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: cc49fb3f8e
// Version Date: Пн авг 31 19:09:04 UTC 2020

// Package grpc provides a gRPC client for the History service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ekudinov/grpc-test/backend/history/proto"
	"github.com/ekudinov/grpc-test/backend/history/service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.HistoryServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var getallEndpoint endpoint.Endpoint
	{
		getallEndpoint = grpctransport.NewClient(
			conn,
			"proto.History",
			"GetAll",
			EncodeGRPCGetAllRequest,
			DecodeGRPCGetAllResponse,
			pb.GetAllResponse{},
			clientOptions...,
		).Endpoint()
	}

	var clearEndpoint endpoint.Endpoint
	{
		clearEndpoint = grpctransport.NewClient(
			conn,
			"proto.History",
			"Clear",
			EncodeGRPCClearRequest,
			DecodeGRPCClearResponse,
			pb.ClearResponse{},
			clientOptions...,
		).Endpoint()
	}

	var addeventEndpoint endpoint.Endpoint
	{
		addeventEndpoint = grpctransport.NewClient(
			conn,
			"proto.History",
			"AddEvent",
			EncodeGRPCAddEventRequest,
			DecodeGRPCAddEventResponse,
			pb.AddEventResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		GetAllEndpoint:   getallEndpoint,
		ClearEndpoint:    clearEndpoint,
		AddEventEndpoint: addeventEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCGetAllResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getall reply to a user-domain getall response. Primarily useful in a client.
func DecodeGRPCGetAllResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetAllResponse)
	return reply, nil
}

// DecodeGRPCClearResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC clear reply to a user-domain clear response. Primarily useful in a client.
func DecodeGRPCClearResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.ClearResponse)
	return reply, nil
}

// DecodeGRPCAddEventResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC addevent reply to a user-domain addevent response. Primarily useful in a client.
func DecodeGRPCAddEventResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.AddEventResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCGetAllRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getall request to a gRPC getall request. Primarily useful in a client.
func EncodeGRPCGetAllRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HistoryRequest)
	return req, nil
}

// EncodeGRPCClearRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain clear request to a gRPC clear request. Primarily useful in a client.
func EncodeGRPCClearRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HistoryRequest)
	return req, nil
}

// EncodeGRPCAddEventRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain addevent request to a gRPC addevent request. Primarily useful in a client.
func EncodeGRPCAddEventRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.AddEventRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
