// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: cc49fb3f8e
// Version Date: Пн авг 31 19:09:04 UTC 2020

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ekudinov/grpc-test/backend/calculator/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC CalculatorServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.CalculatorServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// calculator

		add: grpctransport.NewServer(
			endpoints.AddEndpoint,
			DecodeGRPCAddRequest,
			EncodeGRPCAddResponse,
			serverOptions...,
		),
		sub: grpctransport.NewServer(
			endpoints.SubEndpoint,
			DecodeGRPCSubRequest,
			EncodeGRPCSubResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the CalculatorServer interface
type grpcServer struct {
	add grpctransport.Handler
	sub grpctransport.Handler
}

// Methods for grpcServer to implement CalculatorServer interface

func (s *grpcServer) Add(ctx context.Context, req *pb.Request) (*pb.Response, error) {
	_, rep, err := s.add.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.Response), nil
}

func (s *grpcServer) Sub(ctx context.Context, req *pb.Request) (*pb.Response, error) {
	_, rep, err := s.sub.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.Response), nil
}

// Server Decode

// DecodeGRPCAddRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC add request to a user-domain add request. Primarily useful in a server.
func DecodeGRPCAddRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.Request)
	return req, nil
}

// DecodeGRPCSubRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC sub request to a user-domain sub request. Primarily useful in a server.
func DecodeGRPCSubRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.Request)
	return req, nil
}

// Server Encode

// EncodeGRPCAddResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain add response to a gRPC add reply. Primarily useful in a server.
func EncodeGRPCAddResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.Response)
	return resp, nil
}

// EncodeGRPCSubResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain sub response to a gRPC sub reply. Primarily useful in a server.
func EncodeGRPCSubResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.Response)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
