// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: cc49fb3f8e
// Version Date: Пн авг 31 19:09:04 UTC 2020

// Package grpc provides a gRPC client for the Calculator service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/ekudinov/grpc-test/backend/calculator/proto"
	"github.com/ekudinov/grpc-test/backend/calculator/service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.CalculatorServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var addEndpoint endpoint.Endpoint
	{
		addEndpoint = grpctransport.NewClient(
			conn,
			"proto.Calculator",
			"Add",
			EncodeGRPCAddRequest,
			DecodeGRPCAddResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	var subEndpoint endpoint.Endpoint
	{
		subEndpoint = grpctransport.NewClient(
			conn,
			"proto.Calculator",
			"Sub",
			EncodeGRPCSubRequest,
			DecodeGRPCSubResponse,
			pb.Response{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		AddEndpoint: addEndpoint,
		SubEndpoint: subEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCAddResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC add reply to a user-domain add response. Primarily useful in a client.
func DecodeGRPCAddResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// DecodeGRPCSubResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC sub reply to a user-domain sub response. Primarily useful in a client.
func DecodeGRPCSubResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Response)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCAddRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain add request to a gRPC add request. Primarily useful in a client.
func EncodeGRPCAddRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Request)
	return req, nil
}

// EncodeGRPCSubRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain sub request to a gRPC sub request. Primarily useful in a client.
func EncodeGRPCSubRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Request)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
