// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: cc49fb3f8e
// Version Date: Пн авг 31 19:09:04 UTC 2020

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/ekudinov/grpc-test/backend/history/proto"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	GetAllEndpoint   endpoint.Endpoint
	ClearEndpoint    endpoint.Endpoint
	AddEventEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) GetAll(ctx context.Context, in *pb.HistoryRequest) (*pb.GetAllResponse, error) {
	response, err := e.GetAllEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetAllResponse), nil
}

func (e Endpoints) Clear(ctx context.Context, in *pb.HistoryRequest) (*pb.ClearResponse, error) {
	response, err := e.ClearEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ClearResponse), nil
}

func (e Endpoints) AddEvent(ctx context.Context, in *pb.AddEventRequest) (*pb.AddEventResponse, error) {
	response, err := e.AddEventEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.AddEventResponse), nil
}

// Make Endpoints

func MakeGetAllEndpoint(s pb.HistoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.HistoryRequest)
		v, err := s.GetAll(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeClearEndpoint(s pb.HistoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.HistoryRequest)
		v, err := s.Clear(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeAddEventEndpoint(s pb.HistoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.AddEventRequest)
		v, err := s.AddEvent(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"GetAll":   {},
		"Clear":    {},
		"AddEvent": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetAll" {
			e.GetAllEndpoint = middleware(e.GetAllEndpoint)
		}
		if inc == "Clear" {
			e.ClearEndpoint = middleware(e.ClearEndpoint)
		}
		if inc == "AddEvent" {
			e.AddEventEndpoint = middleware(e.AddEventEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"GetAll":   {},
		"Clear":    {},
		"AddEvent": {},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc := range included {
		if inc == "GetAll" {
			e.GetAllEndpoint = middleware("GetAll", e.GetAllEndpoint)
		}
		if inc == "Clear" {
			e.ClearEndpoint = middleware("Clear", e.ClearEndpoint)
		}
		if inc == "AddEvent" {
			e.AddEventEndpoint = middleware("AddEvent", e.AddEventEndpoint)
		}
	}
}
