// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: cc49fb3f8e
// Version Date: Пн авг 31 19:09:04 UTC 2020

package main

import (
	"flag"

	// This Service
	"github.com/ekudinov/grpc-test/backend/calculator/service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
